# Stage 1: Build the war file
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app

# Copy the project files to the working directory
COPY . .

# Run the Maven wrapper to build the project
RUN mvn clean package

# Stage 2: Deploy the war file to Tomcat 10
FROM tomcat:10.1
WORKDIR /usr/local/tomcat/webapps/

# Copy the wait-for-it script
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

# Copy the war file from the build stage to the Tomcat webapps directory
COPY --from=build /app/target/*.war /usr/local/tomcat/webapps/smarthome.war

# Expose port 8080
EXPOSE 8080

# Start Tomcat server
CMD ["wait-for-it.sh", "db:3306", "--", "catalina.sh", "run"]
