version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: mysql:latest
    container_name: smarthomedb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: group6
      MYSQL_DATABASE: smarthomedb
      MYSQL_USER: group6
      MYSQL_PASSWORD: group6
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:
