@startuml

title UC: Add Actuator to Device\nREST API\n(Process View Level 3)
autonumber

participant "RESTController" as RC
participant "Service" as S
participant "Repository" as R
participant "Domain" as D

[o-> RC : (GET) Request actuator types
activate RC
RC -> S: Get actuator type ids
activate S
S -> R: Get actuator type ids
activate R
R --> S: actuator type ids
deactivate R
deactivate D
S --> RC: actuator type ids
deactivate S
[o<--RC : OK 200, Provide actuator types
deactivate RC

[o-> RC : (GET) Request actuator models(Actuator type)
activate RC
RC -> S: Get actuator model names
activate S
S -> R: Get actuator model names
activate R
R --> S: actuator model names
deactivate R
deactivate D
S --> RC: actuator model names
deactivate S
[o<--RC : OK 200, Provide actuator models
deactivate RC

[o-> RC: (POST) Request add actuator to device(Actuator model)
activate RC
RC -> S: Actuator data
activate S
S -> R : Validation of actuator data
activate R
R --> S : Actuator data validated
deactivate R
S -> D : Create actuator
activate D
D --> S: actuator
deactivate D
S -> R: Save actuator
activate R
R --> S: Actuator added
deactivate R
S --> RC: Actuator added
deactivate S
[o<-- RC: 201 Created, Actuator added
deactivate RC

@enduml